version: '3'

services:
  sojanode0:
    image: sojahub/sojanode:latest
    ports:
      - 1317:1317
      - 26656:26656
      - 26657:26657
    environment:
      CHAINNET: ${CHAINNET0}
      MONIKER: sojanode0
      MNEMONIC: ${MNEMONIC}
      BIND_IP_ADDRESS: ${IPADDR0}
    volumes:
      - ./sojanode/root/scripts:/root/scripts:Z
    command: /root/scripts/sojanode.sh
    networks:
      sojahub:
        ipv4_address: ${IPADDR0}

  sojanode1:
    image: sojahub/sojanode:latest
    ports:
      - 2317:1317
      - 36656:26656
      - 36657:26657
    environment:
      CHAINNET: ${CHAINNET1}
      MONIKER: sojanode1
      MNEMONIC: ${MNEMONIC}
      BIND_IP_ADDRESS: ${IPADDR1}
    volumes:
      - ./sojanode/root/scripts:/root/scripts:Z
    command: /root/scripts/sojanode.sh
    networks:
      sojahub:
        ipv4_address: ${IPADDR1}

  ts-relayer:
    image: sojahub/ts-relayer:latest
    environment:
      CHAINNET0: ${CHAINNET0}
      CHAINNET1: ${CHAINNET1}
      RELAYER_SRC: ${CHAINNET0}
      RELAYER_DEST: ${CHAINNET1}
      SOJANODE0_MNEMONIC: ${MNEMONIC}
      SOJANODE1_MNEMONIC: ${MNEMONIC}
      RPC0: ${IPADDR0}:26657
      RPC1: ${IPADDR1}:26657
      PREFIX0: soja
      PREFIX1: soja
      GAS_PRICE0: "0.5fury"
      GAS_PRICE1: "0.5fury"
    volumes:
      - ./ts-relayer/root/scripts:/root/scripts:Z
    depends_on:
      - sojanode0
      - sojanode1
    command: /root/scripts/ts-relayer.sh
    networks:
      sojahub:
        ipv4_address: ${IPADDR2}

networks:
  sojahub:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
